/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package imageMerge;

import lombok.extern.slf4j.Slf4j;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

@Slf4j class AppTest {
    @Test void appHasAGreeting() {
        App app = new App();
        assertNotNull(app.getGreeting(), "app should have a greeting");
    }
}
