/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package imageMerge;

import lombok.extern.slf4j.Slf4j;

@Slf4j public class App {

    public String getGreeting() {
        return "You will never see this message in log window";
    }

    public static void main(String[] args) {
        log.debug("The app has been started");
    }

}
